openapi: 3.0.3
info:
  title: schema
  version: 1.0.0
  description: 운동 기록을 공유하는 SNS 서비스
paths:
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /record/:
    get:
      operationId: record_list
      description: 로그인을 한 유저가 생성했던 운동기록을 모두 가져옵니다.
      tags:
      - record
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Record'
          description: ''
    post:
      operationId: record_create
      description: API endpoint that allows users to be viewed or edited.
      tags:
      - record
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Record'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Record'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Record'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Record'
          description: ''
  /record/{id}/:
    get:
      operationId: record_retrieve
      description: API endpoint that allows users to be viewed or edited.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this 운동 기록.
        required: true
      tags:
      - record
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Record'
          description: ''
    put:
      operationId: record_update
      description: API endpoint that allows users to be viewed or edited.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this 운동 기록.
        required: true
      tags:
      - record
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Record'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Record'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Record'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Record'
          description: ''
    patch:
      operationId: record_partial_update
      description: API endpoint that allows users to be viewed or edited.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this 운동 기록.
        required: true
      tags:
      - record
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedRecord'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedRecord'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedRecord'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Record'
          description: ''
    delete:
      operationId: record_destroy
      description: API endpoint that allows users to be viewed or edited.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this 운동 기록.
        required: true
      tags:
      - record
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /record/{id}/static_map/:
    post:
      operationId: record_static_map_create
      description: 로그인을 한 유저가 생성했던 운동기록의 StaticMap을 가져옵니다.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - record
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordStaticMap'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/RecordStaticMap'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/RecordStaticMap'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecordStaticMap'
          description: ''
components:
  schemas:
    KindEnum:
      enum:
      - RUN
      - WALK
      - BICYCLE
      type: string
      description: |-
        * `RUN` - 걷기
        * `WALK` - 뛰기
        * `BICYCLE` - 자전거
    PatchedRecord:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        start_at:
          type: string
          format: date-time
          nullable: true
        end_at:
          type: string
          format: date-time
          nullable: true
        static_map:
          type: string
          format: uri
        coords:
          type: string
          description: GPS데이터
        distance:
          type: number
          format: double
          description: 운동한 거리
        speed:
          type: number
          format: double
          description: 평균 속력
        created_at:
          type: string
          format: date-time
          readOnly: true
        kind:
          allOf:
          - $ref: '#/components/schemas/KindEnum'
          description: |-
            운동 종류

            * `RUN` - 걷기
            * `WALK` - 뛰기
            * `BICYCLE` - 자전거
        user:
          type: integer
    Record:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        start_at:
          type: string
          format: date-time
          nullable: true
        end_at:
          type: string
          format: date-time
          nullable: true
        static_map:
          type: string
          format: uri
        coords:
          type: string
          description: GPS데이터
        distance:
          type: number
          format: double
          description: 운동한 거리
        speed:
          type: number
          format: double
          description: 평균 속력
        created_at:
          type: string
          format: date-time
          readOnly: true
        kind:
          allOf:
          - $ref: '#/components/schemas/KindEnum'
          description: |-
            운동 종류

            * `RUN` - 걷기
            * `WALK` - 뛰기
            * `BICYCLE` - 자전거
        user:
          type: integer
      required:
      - coords
      - created_at
      - distance
      - id
      - speed
      - user
    RecordStaticMap:
      type: object
      properties:
        static_map:
          type: string
          format: uri
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
