# Generated by Django 5.0 on 2023-12-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(
                blank=True, help_text="태그", related_name="courses", to="course.tag"
            ),
        ),
    ]
