# Generated by Django 5.0 on 2023-12-12 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='data',
            new_name='coords',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='finished_at',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='created_at',
            new_name='start_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_update',
        ),
        migrations.AlterField(
            model_name='record',
            name='kind',
            field=models.CharField(help_text='enum(walk, run, bicycle)', max_length=50),
        ),
        migrations.CreateModel(
            name='RecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='record/images/%Y/%m/%d/')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record')),
            ],
            options={
                'verbose_name': '인증샷',
            },
        ),
    ]
