name: Django CI

on:
  push:
    branches: ['CI/CD', 'dev']
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.10.6, 3.11, 3.12]

    steps:
      - uses: actions/checkout@v3
      - name: 파이썬 ${{ matrix.python-version }} 설치
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: 환경 벼수 설정
        run: |
          echo {{secrets.BUCKET_NAME}} >> .env
          echo {{secrets.DB_REMOTE_HOST}} >> .env
          echo {{secrets.DB_REMOTE_PW}} >> .env
          echo {{secrets.DB_REMOTE_USERNAME}} >> .env
          echo {{secrets.DEBUG}} >> .env
          echo {{secrets.S3_ACCESS_KEY}} >> .env
          echo {{secrets.S3_SECRET_ACCESS_KEY}} >> .env
          echo {{secrets.SECRET_KEY}} >> .env
      - name: 모듈 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install binutils libproj-dev gdal-bin

      - name: 테스트
        run: |
          python manage.py test
