name: Django CI

on:
  push:
    branches: ['CI/CD', 'dev']
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.10.6, 3.11, 3.12]

    env:
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      DEBUG: ${{secrets.DEBUG}}
      S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
      S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
      DB_REMOTE_HOST: ${{secrets.DB_REMOTE_HOST}}
      DB_REMOTE_PW: ${{secrets.DB_REMOTE_PW}}
      DB_REMOTE_USERNAME: ${{secrets.DB_REMOTE_USERNAME}}
      BUCKET_NAME: ${{secrets.BUCKET_NAME}}

    steps:
      - uses: actions/checkout@v3
      - name: 파이썬 ${{ matrix.python-version }} 설치
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: 모듈 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install binutils libproj-dev gdal-bin

      - name: 테스트
        run: |
          python manage.py test
